### PR TITLE
Add Email Field to Ask a Question Form

### LINKED ISSUE #226: Improve Ask a Question feature when not signed in
Two potential approaches:

* Have a modal when the screen _mounts_ (similar to the comments screen) that prompts users to sign up/sign in. It would be mega annoying to type out a long question, then click send, get an error alert and lose the contents of my message.
* Detect when a user is not logged in and add an input field for email address.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=629603528)

### PR DESCRIPTION
**Pull request by JonEsparaz**
Closes #226.

Email field is required. If the user is signed-in, it will pre-fill with their email address.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=645694663)

### CODE REVIEW

**Comment by GeorgeBellTMH** [comment]
@lucastbelem do we need the email address? Are we ok with optionally letting people be anonymous?

**Comment by JonEsparaz** [comment]
In case this was missed. @deeinstereo said https://github.com/themeetinghouse/mobile/issues/226#issuecomment-767168375:
> I want to make this as accessible as possible, but also want to have a follow up if need be. Can we just add the email as a required field, and then you can submit a question?

**Comment by GeorgeBellTMH** [comment]
k sounds good...will push everything tomorrow...

**Pull request merged**
