### PR TITLE
Fix header height

### LINKED ISSUE #111: Some headers are too tall
image

The screenshot on the left contains a header that is too tall. We currently have a mix of headers set via React Navigation and others that are in the markup using Native Base's `<Header/>`. From what I can tell, the issue is only with the Native Base headers.

This issue wasn't there when I initially built everything, so this happened because of iOS14 and/or Expo SDK 39.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588046175)

### PR DESCRIPTION
**Pull request by JonEsparaz**
I did this a while ago, but forgot the open the PR. Fixes #111.

Also, a small bug fix for navigation within sign-up/sign-in.

Tested on iOS (iPhone 11) and Android (Pixel 3 emulator).

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=595292830)

### CODE REVIEW

**Comment by GeorgeBellTMH** [comment]
image

Doesn't look like this works right...

**Comment by JonEsparaz** [comment]
More detail please. Is this an XCode emulator? If so, what MacOS, XCode versions are you running? Which iPhone model?

I am fairly confident in my testing, so this could be an emulator issue, but I can't be sure since I don't have access to a Mac.

**Comment by GeorgeBellTMH** [comment]
Emulator - iPhone 11 Pro Max…iOS 14.0

G

**Comment by JonEsparaz** [comment]
Did you experience this bug on multiple iPhone models? Did you experience this when using the Expo client (assuming you have access to a physical iPhone)?

**Comment by GeorgeBellTMH** [comment]
It’s just in the expo client, but it is usually accurate from my experience…I didn’t check other models…I’m just finishing something up and then I can run through them all...

**Comment by JonEsparaz** [comment]
Don't worry about re-testing this PR. I'm just going to redo since the big headers look really weird. I'll have something in ~15 mins.

**Pull request merged**
